package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import bookshop.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import bookshop.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import bookshop.*;
import java.io.*;
import java.util.*;
import java.sql.*;
import java.util.*;
import java.text.*;
import bookshop.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.Vector _jspx_dependants;

  static {
    _jspx_dependants = new java.util.Vector(6);
    _jspx_dependants.add("/incoming/common.jsp");
    _jspx_dependants.add("/incoming/header.jsp");
    _jspx_dependants.add("/left.jsp");
    _jspx_dependants.add("/caidan.jsp");
    _jspx_dependants.add("/dingdangonggao.jsp");
    _jspx_dependants.add("/incoming/footer.jsp");
  }

  public java.util.List getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html;charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url();\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	java.util.Date cur_time = new java.util.Date();
	SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
	String dateString = formatter.format(cur_time);
	
	SimpleDateFormat _formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
	String _dateString = _formatter.format(cur_time);

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>航院电子书店书店</title>\r\n");
      out.write("<META HTTP-EQUIV=\"Pragma\" CONTENT=\"no-cache\"> \r\n");
      out.write("<META HTTP-EQUIV=\"Cache-Control\" CONTENT=\"no-cache\"> \r\n");
      out.write("<META HTTP-EQUIV=\"Expires\" CONTENT=\"0\"> \r\n");
      out.write("<link href=\"incoming/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function checkform() {\r\n");
      out.write("\tif (form1.userid.value.length<1 || form1.userid.value.length>15){\r\n");
      out.write("\t\talert(\"请输入正确的用户名！\");\r\n");
      out.write("\t\tform1.userid.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (form1.password.value.length<1 || form1.password.value.length>15){\r\n");
      out.write("\t\talert(\"请输入正确的密码!\");\r\n");
      out.write("\t\tform1.password.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("function checkform1() {\r\n");
      out.write("\tif(document.form2.shousuo.value==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t     alert(\"请输入查询条件!\");\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url();\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-left: 100px;\r\n");
      out.write("\tmargin-right: 100px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("a:link {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("a:active {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write(".style2 {font-size: 16pt}\r\n");
      out.write("-->\r\n");
      out.write("</style></head>\r\n");
      out.write("<body>\r\n");
      out.write("\t    ");

		DBSQLManager dbsm = new DBSQLManager();
		String sql="SELECT NOTICE FROM notice";
		dbsm.setSqlStr(sql);
		dbsm.executeQuery();
		ResultSet rs=dbsm.getRs();
		rs.next();
	 

      out.write(" \r\n");
      out.write("<table width=\"800\" border=\"0\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#F0FFEC\">\r\n");
      out.write("<form name=\"form2\" method=\"post\" action=\"search.jsp\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"55%\" height=\"25\" bgcolor=\"#F0F0E5\">\r\n");
      out.write("        <div align=\"right\">\r\n");
      out.write("          ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<script language=\"javascript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("function MM_openBrWindows(theURL,winName,features)\r\n");
      out.write("{//v2.0\r\n");
      out.write("windows.open(theURL,winName,features);\r\n");
      out.write("}\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write(".STYLE3 {color: #0000CC}\r\n");
      out.write("a:link {\r\n");
      out.write("\tcolor: #0033FF;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("a:active {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("body {\r\n");
      out.write("\tmargin-left: 100px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 100px;\r\n");
      out.write("\tbackground-image: url();\r\n");
      out.write("\tbackground-color: #D5D5D5;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style><div align=\"center\">\r\n");

		DBSQLManager dbsm6 = new DBSQLManager();
		String sql6="SELECT NOTICE FROM notice";
		dbsm6.setSqlStr(sql6);
		dbsm6.executeQuery();
		ResultSet rs6=dbsm6.getRs();
		rs6.next();
		
	 

      out.write("\r\n");
      out.write("<div align=\"center\"></div>\r\n");
      out.write("<table width=\"802\" height=\"143\" border=\"1\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#F0FFEC\" bgcolor=\"#FFFFFF\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"800\" height=\"141\"><table width=\"800\" border=\"0\">\r\n");
      out.write("      <tr>\r\n");
      out.write("        <td width=\"554\" height=\"15\">航 院 电 子 书 店</td>\r\n");
      out.write("        <td width=\"228\"><div align=\"right\">\r\n");
      out.write("            <p><span onclick=\"var strHref=window.location.href;this.style.behavior='url(#default#homepage)';this.setHomePage('航院电子书店');\" style=\"CURSOR: hand; color: #0000FF;\">设为首页</span> || <span style=\"CURSOR: hand; color: #0000FF;\" onClick=\"window.external.addFavorite('http://localhost:8080/bookshop/','航院电子书店')\" title=\"航院电子书店\">收藏本站</span> || <a href=\"admin/login.jsp\">网站管理</a></p>\r\n");
      out.write("        </div></td>\r\n");
      out.write("      </tr>\r\n");
      out.write("    </table>\r\n");
      out.write("      <table width=\"798\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"800\" height=\"66\" align=\"center\"><div align=\"left\">\r\n");
      out.write("            <p><img src=\"images/01_1.gif\" width=\"796\" height=\"62\"></p>\r\n");
      out.write("          </div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>\r\n");
      out.write("      <table width=\"800\" height=\"34\" bordercolor=\"#FFFFFF\" background=\"images/dhbg2.gif\" id=\"table\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"86%\" height=\"28\" valign=\"top\" class=\"table\">\r\n");
      out.write("            <MARQUEE id=zimu onmouseover=zimu.stop() onmouseout=zimu.start() \r\n");
      out.write("      scrollDelay=200 align=\"middle\">\r\n");
      out.write("            <table width=\"784\" height=\"21\">\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td width=\"776\">");
      out.print(rs6.getString("NOTICE"));
      out.write("</td>\r\n");
      out.write("              </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("            </marquee>\r\n");
      out.write("          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table>            <table width=\"800\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"90\"><div align=\"right\"><a href=\"index.jsp\">首页</a></div></td>\r\n");
      out.write("          <td width=\"90\"><div align=\"right\"><a href=\"bookfenlei.jsp\">图书分类</a></div></td>\r\n");
      out.write("          <td width=\"90\"><div align=\"right\"><a href=\"booklist.jsp\">选购图书</a></div></td>\r\n");
      out.write("          <td width=\"90\"><div align=\"right\"><a href=\"shopcar.jsp\">我的购物车</a></div></td>\r\n");
      out.write("          <td width=\"90\" height=\"20\"><div align=\"right\"><a href=\"myshop.jsp\">我的订单</a> </div></td>\r\n");
      out.write("          <td width=\"90\"><div align=\"right\">邮购信息</div></td>\r\n");
      out.write("          <td width=\"90\" align=\"right\"> <div align=\"right\">关于我们</div></td><td width=\"168\" align=\"right\"><div align=\"right\">当前日期:");
      out.print(dateString);
      out.write("</div></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("    </table></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("        图书查询：\r\n");
      out.write("          <input name=\"shousuo\" type=\"text1\" id=\"userid2\" size=\"25\" maxlength=\"60\">\r\n");
      out.write("          <input type=\"submit\" name=\"Submit3\" value=\"确定\" onclick=\"javascript:return(checkform1());\">\r\n");
      out.write("      </div></td></tr>\r\n");
      out.write("</form>\r\n");
      out.write("</table>\r\n");
      out.write("<table width=\"802\" height=\"358\" border=\"1\" align=\"center\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#F0FFEC\" bgcolor=\"#F0F0E5\">\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"167\" rowspan=\"2\"><div align=\"center\"></div>      <p align=\"center\">");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>航院电子书店书店</title>\r\n");
      out.write("<link href=\"incoming/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<script language=\"javascript\">\r\n");
      out.write("function checkform() {\r\n");
      out.write("\tif (form1.userid.value.length<1 || form1.userid.value.length>15){\r\n");
      out.write("\t\talert(\"请输入正确的用户名！\");\r\n");
      out.write("\t\tform1.userid.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\tif (form1.password.value.length<1 || form1.password.value.length>15){\r\n");
      out.write("\t\talert(\"请输入正确的密码!\");\r\n");
      out.write("\t\tform1.password.focus();\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("function checkform1() {\r\n");
      out.write("\tif(document.form2.shousuo.value==\"\")\r\n");
      out.write("\t{\r\n");
      out.write("\t     alert(\"请输入查询条件!\");\r\n");
      out.write("\t\t  return false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url();\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-left: 100px;\r\n");
      out.write("\tmargin-right: 100px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("a:link {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("a:active {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style></head>\r\n");
      out.write("<body>\r\n");
if(session.getAttribute("userid")==null){
      out.write("\r\n");
      out.write("        <div align=\"center\">用户登录 </div>\r\n");
      out.write("        <form name=\"form1\" method=\"post\" action=\"chklogin.jsp\">\r\n");
      out.write("          <table width=\"100%\" height=\"107\" border=\"1\" cellpadding=\"0\" cellspacing=\"0\" bordercolor=\"#CCCCCC\">\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td width=\"45%\" height=\"26\" align=\"right\">用户名: </td>\r\n");
      out.write("              <td width=\"55%\"><input name=\"userid\" type=\"text\" id=\"userid2\" size=\"10\" maxlength=\"25\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td height=\"22\" align=\"right\">密 码: </td>\r\n");
      out.write("              <td>\r\n");
      out.write("                <input name=\"password\" type=\"password\" id=\"password\" size=\"10\" maxlength=\"25\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td height=\"34\" colspan=\"2\" align=\"center\">\r\n");
      out.write("                <div align=\"center\">\r\n");
      out.write("                  <input type=\"submit\" name=\"Submit\" value=\"登录\" \r\n");
      out.write("onclick=\"javascript:return(checkform());\">\r\n");
      out.write("                  <input type=\"reset\" name=\"Submit2\" value=\"取消\">\r\n");
      out.write("                </div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("              <td height=\"15\" colspan=\"2\"><div align=\"center\"> 新用户<a href=\"register.jsp\">| 注册 |</a><a href=\"zhaohuimima1.jsp\"> 找回密码 | </a></div></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("        </form>\r\n");
      out.write("\t\t ");
}else{
      out.write("\r\n");
      out.write("        <table width=\"100%\" height=\"99\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("          <tr>\r\n");
      out.write("            <td width=\"8%\">&nbsp;</td>\r\n");
      out.write("            <td width=\"92%\" height=\"112\" valign=\"top\" background=\"Images/index_09.gif\">\r\n");
      out.write("              <table width=\"100%\"  border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td width=\"8%\" height=\"20\">&nbsp;</td>\r\n");
      out.write("                  <td width=\"81%\">&nbsp;</td>\r\n");
      out.write("                  <td width=\"11%\">&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td>&nbsp;</td>\r\n");
      out.write("\t\t\t\t  \r\n");
      out.write("                  <td height=\"24\" align=\"center\"><div align=\"center\"><img src=\"images/touxiang%20.gif\" width=\"29\" height=\"27\">[ ");
      out.print(session.getAttribute("userid"));
      out.write("]您好！</div></td>\r\n");
      out.write("                  <td>&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                ");

				/*ResultSet rs=connDB.executeQuery("select * from tb_Member where Username='"+session.getAttribute("UserName")+"'");
				int grade=0;
				if(rs_grade.next()){
					grade=rs_grade.getInt("grade");
				}*/
				
      out.write("\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td>&nbsp;</td>\r\n");
      out.write("                  <td height=\"31\" align=\"center\"> &nbsp;\r\n");
      out.write("\t\t\t\t    <div align=\"center\">\r\n");
      out.write("                      <input type=\"submit\" name=\"Submit\" value=\"修改资料\" class=\"btn_grey\" onClick=\"window.location.href='modifyuserinfo.jsp'\">\r\n");
      out.write("                        <input name=\"Submit22\" type=\"button\" class=\"btn_grey\" value=\"退出\" onClick=\"window.location.href='logout.jsp'\">\r\n");
      out.write("\t\t          </div></td>\r\n");
      out.write("                  <td>&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td>&nbsp;</td>\r\n");
      out.write("                  <td align=\"center\">&nbsp;</td>\r\n");
      out.write("                  <td>&nbsp;</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("\t\t");
}
      out.write("\r\n");
      out.write("        <p align=\"center\">&nbsp;</p>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("      </p>      <div align=\"center\"><img src=\"images/show.gif\" width=\"110\" height=\"177\">\r\n");
      out.write("    </div></td>\r\n");
      out.write("    <td height=\"304\"><p align=\"center\"><a class=\"style2\">新书推荐</a></p>\r\n");
      out.write("      <table width=\"98%\" height=\"271\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("        <tr>\r\n");
      out.write("          <td width=\"515\" height=\"220\" valign=\"top\">\r\n");
      out.write("            <table width=\"100%\" height=\"156\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("              ");

                   DBSQLManager dbsm1 = new DBSQLManager();
                   String sql1="select top 4 * from bookinfo order by BOOK_DATE desc";
                   dbsm1.setSqlStr(sql1);
                  dbsm1.executeQuery();
                   ResultSet rs1=dbsm1.getRs();
				 
				   int i=0;
                   while(rs1.next())
				   {
				      i++ ;    
				      if(i>4)
		                    break;
			          if ((i%2)!=0){
			  
      out.write("\r\n");
      out.write("              <tr>\r\n");
      out.write("                <td height=\"156\"><table width=\"100%\" height=\"123\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                    <tr>\r\n");
      out.write("                      <td width=\"43%\" align=\"center\"><img src=\"bookpicture/");
      out.print(rs1.getString("BOOKPICTURE"));
      out.write("\" width=\"93\" height=\"116\"></td>\r\n");
      out.write("                      <td width=\"57%\"><table width=\"100%\" height=\"120\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>ISBN:");
      out.print(rs1.getString("ISBN"));
      out.write("</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>书名:");
      out.print(rs1.getString("TITLE"));
      out.write("</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                          <tr>\r\n");
      out.write("                            <td>作者：");
      out.print(rs1.getString("AUTHOR"));
      out.write("</td>\r\n");
      out.write("                          </tr>\r\n");
      out.write("                    <td>定价：");
      out.print(String.valueOf(rs1.getInt("PRICE")));
      out.write("（元）                      </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <td height=\"17\" align=\"center\">&nbsp; </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                      </table></td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                </table>                \r\n");
      out.write("                  <div align=\"right\">\r\n");
      out.write("                    <input type=\"button\" name=\"Submit22\" value=\"查看\"onClick=\"window.location.href='bookchakan.jsp?isbn=");
      out.print(rs1.getString("ISBN"));
      out.write("'\">\r\n");
      out.write("                </div></td>\r\n");
      out.write("                ");
 }else{
      out.write("\r\n");
      out.write("                <td><table width=\"113%\" height=\"123\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                  <tr>\r\n");
      out.write("                    <td width=\"43%\" align=\"center\"><img src=\"bookpicture/");
      out.print(rs1.getString("BOOKPICTURE"));
      out.write("\" width=\"91\" height=\"111\"></td>\r\n");
      out.write("                    <td width=\"57%\"><table width=\"99%\" height=\"119\"  border=\"0\" cellpadding=\"0\" cellspacing=\"0\">\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td>ISBN:");
      out.print(rs1.getString("ISBN"));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td>书名:");
      out.print(rs1.getString("TITLE"));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("                        <tr>\r\n");
      out.write("                          <td>作者：");
      out.print(rs1.getString("AUTHOR"));
      out.write("</td>\r\n");
      out.write("                        </tr>\r\n");
      out.write("        <td>定价：");
      out.print(String.valueOf(rs1.getInt("PRICE")));
      out.write("（元）          </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <td align=\"center\">&nbsp; </td>\r\n");
      out.write("        </tr>\r\n");
      out.write("                    </table></td>\r\n");
      out.write("                  </tr>\r\n");
      out.write("                </table>\r\n");
      out.write("                  <div align=\"right\">\r\n");
      out.write("                    <input type=\"button\" name=\"Submit2\" value=\"查看\"onClick=\"window.location.href='bookchakan.jsp?isbn=");
      out.print(rs1.getString("ISBN"));
      out.write("'\">\r\n");
      out.write("                </div></td>\r\n");
      out.write("                ");

			}
			//rs1.next();
			}
			
      out.write("\r\n");
      out.write("              </tr>\r\n");
      out.write("          </table>\r\n");
      out.write("          <p>&nbsp;</p></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("      </table></td>\r\n");
      out.write("    <td width=\"135\" rowspan=\"2\"><p align=\"center\">");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>菜单</title>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<STYLE type=\"text/css\">\r\n");
      out.write("A:link { COLOR: #000000; FONT-SIZE: 12px; TEXT-DECORATION: none}\r\n");
      out.write("A:visited { COLOR: #000000; FONT-SIZE: 12px; TEXT-DECORATION: none}\r\n");
      out.write("A:hover { COLOR: #006CD9; FONT-SIZE: 12px; TEXT-DECORATION: none}\r\n");
      out.write("BODY { FONT-SIZE: 12px;}\r\n");
      out.write("TD { FONT-SIZE: 12px; line-height: 150%}\r\n");
      out.write("</style>\r\n");
      out.write("<script language=\"JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("function showitem(id,name)\r\n");
      out.write("{\r\n");
      out.write("\treturn (\"<span><a href='\"+id+\"' target=_blank>\"+name+\"</a></span><br>\")\r\n");
      out.write("}\r\n");
      out.write("function switchoutlookBar(number)\r\n");
      out.write("{\r\n");
      out.write("\tvar i = outlookbar.opentitle;\r\n");
      out.write("\toutlookbar.opentitle=number;\r\n");
      out.write("\tvar id1,id2,id1b,id2b\r\n");
      out.write("\tif (number!=i && outlooksmoothstat==0){\r\n");
      out.write("\t\tif (number!=-1)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif (i==-1){\r\n");
      out.write("\t\t\t\tid2=\"blankdiv\";\r\n");
      out.write("\t\t\t\tid2b=\"blankdiv\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse{\r\n");
      out.write("\t\t\t\tid2=\"outlookdiv\"+i;\r\n");
      out.write("\t\t\t\tid2b=\"outlookdivin\"+i;\r\n");
      out.write("\t\t\t\tdocument.all(\"outlooktitle\"+i).style.border=\"1px none navy\";\r\n");
      out.write("\t\t\t\tdocument.all(\"outlooktitle\"+i).style.background=outlookbar.maincolor;\r\n");
      out.write("\t\t\t\tdocument.all(\"outlooktitle\"+i).style.color=\"#ffffff\";\r\n");
      out.write("\t\t\t\tdocument.all(\"outlooktitle\"+i).style.textalign=\"center\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tid1=\"outlookdiv\"+number\r\n");
      out.write("\t\t\tid1b=\"outlookdivin\"+number\r\n");
      out.write("\t\t\tdocument.all(\"outlooktitle\"+number).style.border=\"1px none white\";\r\n");
      out.write("\t\t\tdocument.all(\"outlooktitle\"+number).style.background=outlookbar.maincolor; //title\r\n");
      out.write("\t\t\tdocument.all(\"outlooktitle\"+number).style.color=\"#ffffff\";\r\n");
      out.write("\t\t\tdocument.all(\"outlooktitle\"+number).style.textalign=\"center\";\r\n");
      out.write("\t\t\tsmoothout(id1,id2,id1b,id2b,0);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.all(\"blankdiv\").style.display=\"\";\r\n");
      out.write("\t\t\tdocument.all(\"blankdiv\").sryle.height=\"100%\";\r\n");
      out.write("\t\t\tdocument.all(\"outlookdiv\"+i).style.display=\"none\";\r\n");
      out.write("\t\t\tdocument.all(\"outlookdiv\"+i).style.height=\"0%\";\r\n");
      out.write("\t\t\tdocument.all(\"outlooktitle\"+i).style.border=\"1px none navy\";\r\n");
      out.write("\t\t\tdocument.all(\"outlooktitle\"+i).style.background=outlookbar.maincolor;\r\n");
      out.write("\t\t\tdocument.all(\"outlooktitle\"+i).style.color=\"#ffffff\";\r\n");
      out.write("\t\t\tdocument.all(\"outlooktitle\"+i).style.textalign=\"center\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function smoothout(id1,id2,id1b,id2b,stat)\r\n");
      out.write("{\r\n");
      out.write("\tif(stat==0){\r\n");
      out.write("\t\ttempinnertext1=document.all(id1b).innerHTML;\r\n");
      out.write("\t\ttempinnertext2=document.all(id2b).innerHTML;\r\n");
      out.write("\t\tdocument.all(id1b).innerHTML=\"\";\r\n");
      out.write("\t\tdocument.all(id2b).innerHTML=\"\";\r\n");
      out.write("\t\toutlooksmoothstat=1;\r\n");
      out.write("\t\tdocument.all(id1b).style.overflow=\"hidden\";\r\n");
      out.write("\t\tdocument.all(id2b).style.overflow=\"hidden\";\r\n");
      out.write("\t\tdocument.all(id1).style.height=\"0%\";\r\n");
      out.write("\t\tdocument.all(id1).style.display=\"\";\r\n");
      out.write("\t\tsetTimeout(\"smoothout('\"+id1+\"','\"+id2+\"','\"+id1b+\"','\"+id2b+\"',\"+outlookbar.inc+\")\",outlookbar.timedalay);\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t{\r\n");
      out.write("\t\tstat+=outlookbar.inc;\r\n");
      out.write("\t\tif (stat>100)\r\n");
      out.write("\t\t\tstat=100;\r\n");
      out.write("\t\tdocument.all(id1).style.height=stat+\"%\";\r\n");
      out.write("\t\tdocument.all(id2).style.height=(100-stat)+\"%\";\r\n");
      out.write("\t\tif (stat<100) \r\n");
      out.write("\t\t\tsetTimeout(\"smoothout('\"+id1+\"','\"+id2+\"','\"+id1b+\"','\"+id2b+\"',\"+stat+\")\",outlookbar.timedalay);\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tdocument.all(id1b).innerHTML=tempinnertext1;\r\n");
      out.write("\t\t\tdocument.all(id2b).innerHTML=tempinnertext2;\r\n");
      out.write("\t\t\toutlooksmoothstat=0;\r\n");
      out.write("\t\t\tdocument.all(id1b).style.overflow=\"auto\";\r\n");
      out.write("\t\t\tdocument.all(id2).style.display=\"none\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function getOutLine()\r\n");
      out.write("{\r\n");
      out.write("\toutline=\"<table \"+outlookbar.otherclass+\">\";\r\n");
      out.write("\tfor (i=0;i<(outlookbar.titlelist.length);i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\toutline+=\"<tr><td name=outlooktitle\"+i+\" id=outlooktitle\"+i+\" \"; \r\n");
      out.write("\t\tif (i!=outlookbar.opentitle) \r\n");
      out.write("\t\t\toutline+=\" nowrap align=center style='cursor:hand;background-color:\"+outlookbar.maincolor+\";color:#ffffff;height:20;border:1 none navy' \";\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\toutline+=\" nowrap align=center style='cursor:hand;background-color:\"+outlookbar.maincolor+\";color:white;height:20;border:1 none white' \";\r\n");
      out.write("\t\toutline+=outlookbar.titlelist[i].otherclass\r\n");
      out.write("\t\toutline+=\" onclick='switchoutlookBar(\"+i+\")'><span class=smallFont>\";\r\n");
      out.write("\t\toutline+=outlookbar.titlelist[i].title+\"</span></td></tr>\";\r\n");
      out.write("\t\toutline+=\"<tr><td name=outlookdiv\"+i+\" valign=top align=center id=outlookdiv\"+i+\" style='width:100%\"\r\n");
      out.write("\t\tif (i!=outlookbar.opentitle) \r\n");
      out.write("\t\t\toutline+=\";display:none;height:0%;\";\r\n");
      out.write("\t\telse\r\n");
      out.write("\t\t\toutline+=\";display:;height:100%;\";\r\n");
      out.write("\t\toutline+=\"'><div name=outlookdivin\"+i+\" id=outlookdivin\"+i+\" style='overflow:auto;width:100%;height:100%'>\";\r\n");
      out.write("\t\tfor (j=0;j<outlookbar.itemlist[i].length;j++)\r\n");
      out.write("\t\t\toutline+=showitem(outlookbar.itemlist[i][j].key,outlookbar.itemlist[i][j].title);\r\n");
      out.write("\t\toutline+=\"</div></td></tr>\"\r\n");
      out.write("\t}\r\n");
      out.write("\toutline+=\"</table>\"\r\n");
      out.write("\treturn outline\r\n");
      out.write("}\r\n");
      out.write("function show()\r\n");
      out.write("{\r\n");
      out.write("\tvar outline;\r\n");
      out.write("\toutline=\"<div id=outLookBarDiv name=outLookBarDiv style='width=100%;height:100%'>\"\r\n");
      out.write("\toutline+=outlookbar.getOutLine();\r\n");
      out.write("\toutline+=\"</div>\"\r\n");
      out.write("\tdocument.write(outline);\r\n");
      out.write("}\r\n");
      out.write("function theitem(intitle,instate,inkey)\r\n");
      out.write("{\r\n");
      out.write("\tthis.state=instate;\r\n");
      out.write("\tthis.otherclass=\" nowrap \";\r\n");
      out.write("\tthis.key=inkey;\r\n");
      out.write("\tthis.title=intitle;\r\n");
      out.write("}\r\n");
      out.write("function addtitle(intitle)\r\n");
      out.write("{\r\n");
      out.write("\toutlookbar.itemlist[outlookbar.titlelist.length]=new Array();\r\n");
      out.write("\toutlookbar.titlelist[outlookbar.titlelist.length]=new theitem(intitle,1,0);\r\n");
      out.write("\treturn(outlookbar.titlelist.length-1);\r\n");
      out.write("}\r\n");
      out.write("function additem(intitle,parentid,inkey)\r\n");
      out.write("{\r\n");
      out.write("\tif (parentid>=0 && parentid<=outlookbar.titlelist.length)\r\n");
      out.write("\t{\r\n");
      out.write("\t\toutlookbar.itemlist[parentid][outlookbar.itemlist[parentid].length]=new theitem(intitle,2,inkey);\r\n");
      out.write("\t\toutlookbar.itemlist[parentid][outlookbar.itemlist[parentid].length-1].otherclass=\" nowrap align=left style='height:5' \";\r\n");
      out.write("\t\treturn(outlookbar.itemlist[parentid].length-1);\r\n");
      out.write("\t}\r\n");
      out.write("\telse\r\n");
      out.write("\t\tadditem=-1;\r\n");
      out.write("}\r\n");
      out.write("function outlook()\r\n");
      out.write("{\r\n");
      out.write("\tthis.titlelist=new Array();\r\n");
      out.write("\tthis.itemlist=new Array();\r\n");
      out.write("\tthis.divstyle=\"style='height:100%;width:100%;overflow:auto' align=center\";\r\n");
      out.write("\tthis.otherclass=\"border=0 cellspacing='0' cellpadding='0' style='height:100%;width:100%'valign=middle align=center \";\r\n");
      out.write("\tthis.addtitle=addtitle;\r\n");
      out.write("\tthis.additem=additem;\r\n");
      out.write("\tthis.starttitle=-1;\r\n");
      out.write("\tthis.show=show;\r\n");
      out.write("\tthis.getOutLine=getOutLine;\r\n");
      out.write("\tthis.opentitle=this.starttitle;\r\n");
      out.write("\tthis.reflesh=outreflesh;\r\n");
      out.write("\tthis.timedelay=50;\r\n");
      out.write("\tthis.inc=10;\r\n");
      out.write("\tthis.maincolor = \"#336699\"\r\n");
      out.write("}\r\n");
      out.write("function outreflesh()\r\n");
      out.write("{\r\n");
      out.write("\tdocument.all(\"outLookBarDiv\").innerHTML=outlookbar.getOutLine();\r\n");
      out.write("}\r\n");
      out.write("function locatefold(foldname)\r\n");
      out.write("{\r\n");
      out.write("\tif (foldname==\"\")\r\n");
      out.write("\t\tfoldname = outlookbar.titlelist[0].title\r\n");
      out.write("\tfor (var i=0;i<outlookbar.titlelist.length;i++)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tif(foldname==outlookbar.titlelist[i].title)\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\toutlookbar.starttitle=i;\r\n");
      out.write("\t\t\toutlookbar.opentitle=i;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("var outlookbar=new outlook();\r\n");
      out.write("var tempinnertext1,tempinnertext2,outlooksmoothstat\r\n");
      out.write("outlooksmoothstat = 0;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("var t;\r\n");
      out.write("t=outlookbar.addtitle('技术文档')\r\n");
      out.write("outlookbar.additem('Web开发',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('数据库',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("t=outlookbar.addtitle('计算机技术')\r\n");
      out.write("outlookbar.additem('操作系统',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('网络安全',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('硬件相关',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("t=outlookbar.addtitle('文摘')\r\n");
      out.write("outlookbar.additem('求职 ',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('杂文 ',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('生活 ',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('人生 ',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('健康 ',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('知识 ',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('寓言 ',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('教育 ',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("outlookbar.additem('散文 ',t,'http://localhost:8080/bookshop/web.html')\r\n");
      out.write("t=outlookbar.addtitle('友情连接')\r\n");
      out.write("outlookbar.additem('当当网 ',t,'http://www.7stk.com/index.asp')\r\n");
      out.write("outlookbar.additem('---- ',t,'http://www.7stk.com/index.asp')\r\n");
      out.write("outlookbar.additem('---- ',t,'http://www.7stk.com/index.asp')\r\n");
      out.write("outlookbar.additem('---- ',t,'http://www.7stk.com/index.asp')\r\n");
      out.write("outlookbar.additem('网易 ',t,'http://www.163.com')\r\n");
      out.write("outlookbar.additem('新浪 ',t,'http://www.sina.com')\r\n");
      out.write("outlookbar.additem('搜狐 ',t,'http://www.sohu.com')\r\n");
      out.write("outlookbar.additem('TOM ',t,'http://www.tom.com')\r\n");
      out.write("outlookbar.additem('辽河华宇 ',t,'http://www.liaohe.com.cn')\r\n");
      out.write("outlookbar.additem('沈阳航院 ',t,'http://www.7stk.com/index.asp')\r\n");
      out.write("outlookbar.additem('格微软件 ',t,'http://www.7stk.com/index.asp')\r\n");
      out.write("\r\n");
      out.write("//-->\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<table id=mnuList style=\"WIDTH:150px;HEIGHT: 100%\" cellspacing=0 cellpadding=0 align=center border=0>\r\n");
      out.write("\t<tr> \r\n");
      out.write("\t\t<td bgcolor=#F0F0E5 id=outLookBarShow style=\"HEIGHT: 100%\" valign=top align=middle name=\"outLookBarShow\">\r\n");
      out.write("\t\t\t<script language=\"JavaScript\">\r\n");
      out.write("\t\t\t<!--\r\n");
      out.write("\t\t\tlocatefold(\"\")\r\n");
      out.write("\t\t\toutlookbar.show() \r\n");
      out.write("\t\t\t//-->\r\n");
      out.write("\t\t\t</script>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("<div align=\"right\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("</p>    \r\n");
      out.write("      <div align=\"left\">      </div></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("  <tr>\r\n");
      out.write("    <td width=\"492\" height=\"52\"><p>\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>航院电子书店书店</title>\r\n");
      out.write("<link href=\"incoming/style.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url();\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-left: 100px;\r\n");
      out.write("\tmargin-right: 100px;\r\n");
      out.write("\tmargin-bottom: 0px;\r\n");
      out.write("}\r\n");
      out.write("a:link {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:visited {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("a:hover {\r\n");
      out.write("\ttext-decoration: underline;\r\n");
      out.write("}\r\n");
      out.write("a:active {\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style></head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("        <div align=\"center\"></div>\r\n");
      out.write("        <div align=\"center\">以送货通知</div>\r\n");
      out.write("        ");

		DBSQLManager dbsm3 = new DBSQLManager();
		String sql3="SELECT * FROM umshitu as a,boshitu as b where a.SONGHUO='1'and a.ORDER_ID=b.ORDER_ID";
		dbsm3.setSqlStr(sql3);
		dbsm3.executeQuery();
		ResultSet rs3=dbsm3.getRs();
	 

      out.write(" \r\n");
      out.write("\r\n");
      out.write("        <table width=\"99%\" height=\"36\" bordercolor=\"#FFFFFF\" id=\"table\">\r\n");
      out.write("          <td height=\"10\"><tr>\r\n");
      out.write("            <td width=\"86%\" height=\"43\" valign=\"top\" class=\"table\">\r\n");
      out.write("              <marquee direction=\"up\" scrollamount=\"1\" scrolldelay=\"1\" height=\"100\" onMouseMove=\"this.stop()\" onMouseOut=\"this.start()\">\r\n");
      out.write("              <table width=\"100%\" height=\"27\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td>\r\n");
      out.write("\t\t\t\t  ");
while(rs3.next()){
                    
      out.print("尊敬的"+rs3.getString("USER_ID")+"您订购的书名为"+rs3.getString("TITLE")+"图书已经发送请注意查收!");
      out.write("<td></td></td>\r\n");
      out.write("                ");
}
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("              </table>\r\n");
      out.write("            </marquee>            </td>\r\n");
      out.write("          </tr>\r\n");
      out.write("</table>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("    </p>\r\n");
      out.write("    <p>&nbsp;      </p></td>\r\n");
      out.write("  </tr>\r\n");
      out.write("</table>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("<!--\r\n");
      out.write("body {\r\n");
      out.write("\tbackground-image: url();\r\n");
      out.write("\tbackground-color: #D5D5D5;\r\n");
      out.write("\tmargin-left: 100px;\r\n");
      out.write("\tmargin-top: 0px;\r\n");
      out.write("\tmargin-right: 100px;\r\n");
      out.write("}\r\n");
      out.write("-->\r\n");
      out.write("</style>\r\n");
      out.write("<div align=\"center\">\r\n");
      out.write("  <table width=\"802\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" background=\"images/004d.gif\">\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td width=\"200\" height=\"13\">&nbsp;</td>\r\n");
      out.write("      <td width=\"400\"><div align=\"center\"> 中国 辽宁 沈阳航空工业学院北方软件学院 5233107</div></td>\r\n");
      out.write("      <td width=\"200\">&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("      <td height=\"13\">&nbsp;</td>\r\n");
      out.write("      <td><div align=\"center\">CopyRight 2007 邮箱：<a href=\"mailto:domybest37@163.com\">domybest37@163.com</a></div></td>\r\n");
      out.write("      <td>&nbsp;</td>\r\n");
      out.write("    </tr>\r\n");
      out.write("  </table>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
