package org.apache.jsp.admin.iframe;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class left_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.Vector _jspx_dependants;

  public java.util.List getDependants() {
    return _jspx_dependants;
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html;charset=gb2312");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      com.bean.SystemBean sn = null;
      synchronized (_jspx_page_context) {
        sn = (com.bean.SystemBean) _jspx_page_context.getAttribute("sn", PageContext.PAGE_SCOPE);
        if (sn == null){
          sn = new com.bean.SystemBean();
          _jspx_page_context.setAttribute("sn", sn, PageContext.PAGE_SCOPE);
        }
      }
      out.write('\r');
      out.write('\n');

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
String dir=sn.getDir();

      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n");
      out.write("<HTML>\r\n");
      out.write("<HEAD>\r\n");
      out.write("<TITLE>系统管理</TITLE>\r\n");
      out.write("<META http-equiv=Content-Language content=zh-cn>\r\n");
      out.write("<META http-equiv=Content-Type content=\"text/html; charset=gb2312\">\r\n");
      out.write("<LINK href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/Admin_Style.css\" rel=stylesheet>\r\n");
      out.write("<META content=\"MSHTML 6.00.2900.3243\" name=GENERATOR>\r\n");
      out.write("</HEAD>\r\n");
      out.write("<SCRIPT language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("<!--\r\n");
      out.write("var array = new Array();//数字顺延\r\n");
      out.write("array[0]=1;array[1]=2;array[2]=3;array[3]=4;array[4]=5;array[5]=6;array[6]=7;array[7]=8;array[8]=9;array[9]=10;\r\n");
      out.write("function expand(id_value){\r\n");
      out.write("  var tmp;\r\n");
      out.write("  eval(\"tmp=document.getElementById('id_\"+id_value+\"').style.display\");\r\n");
      out.write("  if(tmp==''){\r\n");
      out.write("    eval(\"document.getElementById('id_\"+id_value+\"').style.display='none'\");\r\n");
      out.write("  }else{\r\n");
      out.write("   for(i=0;i<array.length;i++){\r\n");
      out.write("      eval(\"document.getElementById('id_\"+array[i]+\"').style.display='none'\");\r\n");
      out.write("  }\r\n");
      out.write("    eval(\"document.getElementById('id_\"+id_value+\"').style.display=''\");\r\n");
      out.write("  }  \r\n");
      out.write(" }\r\n");
      out.write("//-->\r\n");
      out.write("</SCRIPT>\r\n");

	String username=(String)session.getAttribute("user");
	if(username==null){
		response.sendRedirect(path+"/error.jsp");
	}
	else{
	List list=(List)session.getAttribute("list");
	String QX=list.get(4).toString();
	String temp[]=QX.split("/");

      out.write("\r\n");
      out.write("<BODY  oncontextmenu=\"return false;\" onselectstart=\"return false;\" leftMargin=0 background=");
      out.print(basePath );
      out.print(dir );
      out.write("/images/MainBg.gif topMargin=0 scroll=no marginheight=\"0\" marginwidth=\"0\">\r\n");
      out.write("<TABLE bgColor=#eef8fe  class=HeaderTdStyle height=\"100%\" cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("  <TBODY>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD vAlign=top align=middle>\r\n");
      out.write("      <TABLE cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD align=middle ><IMG height=17 src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/sys.gif\" width=21>\r\n");
      out.write("          <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/iframe/main.jsp\" target=\"MainFrame\">管理首页</a>\r\n");
      out.write("          </TD>\r\n");
      out.write("        </TR>\r\n");
      out.write("        </TBODY>\r\n");
      out.write("      </TABLE>\r\n");
      out.write("      <TABLE  bgColor=#eef8fe   height=\"100%\" cellSpacing=0 cellPadding=0 width=\"100%\" border=0>\r\n");
      out.write("        <TBODY>\r\n");
      out.write("        <TR>\r\n");
      out.write("          <TD vAlign=top height=\"100%\">\r\n");
      out.write("          <DIV style=\"OVERFLOW: auto; WIDTH: 100%; HEIGHT: 96%\" align=center>\r\n");
      out.write("<TABLE  bgColor=#eef8fe cellSpacing=0 cellPadding=0 width=\"90%\" align=center border=0>\r\n");
      out.write("  <TBODY> \r\n");
      out.write("  <TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("  <TD noWrap width=\"35%\">\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\"style=\"cursor:hand\" onclick=javascript:expand(1)>\r\n");
      out.write("    <TR>\r\n");
      out.write("    <TD height=\"31\" background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\">&nbsp;</td>\r\n");
      out.write("    <TD background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\" >&nbsp;<IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/menu.gif\" align=absMiddle>系统设置</TD></TR>\r\n");
      out.write("    </TABLE>\r\n");
      out.write("    <TABLE width=\"100%\" border=\"0\" align=\"center\" id=id_1 style=\"display:none\">\r\n");
      out.write("    <TR>\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> \r\n");
      out.write("      <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/system/user.jsp\" target=\"MainFrame\">管理员设置</a></SPAN></TD></TR>\r\n");
      out.write("  \t<TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/system/log.jsp\" target=\"MainFrame\">后台登录日志</a></SPAN></TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("  <TD noWrap width=\"35%\">\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\"style=\"cursor:hand\" onclick=javascript:expand(2)>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=\"31\" background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\">&nbsp;</td>\r\n");
      out.write("    <TD background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\" >&nbsp;<IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/menu.gif\" align=absMiddle>网站设置</TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\" id=id_2 style=\"display:none\">\r\n");
      out.write("   <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/guestbook/index.jsp\" target=\"MainFrame\">留言板管理</a></SPAN></TD></TR>\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/affiche/index.jsp\" target=\"MainFrame\">滚动公告管理</a></SPAN></TD></TR>\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/affiche/edit.jsp?method=addAffiche\" target=\"MainFrame\">发布滚动公告</a></SPAN></TD></TR>\r\n");
      out.write("  \r\n");
      out.write("  </TABLE>\r\n");
      out.write("  </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("  <TD noWrap width=\"35%\">\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\"style=\"cursor:hand\" onclick=javascript:expand(3)>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=\"31\" background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\">&nbsp;</td>\r\n");
      out.write("    <TD background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\" >&nbsp;<IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/menu.gif\" align=absMiddle>新闻资讯</TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\" id=id_3 style=\"display:none\">\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/news/index.jsp\" target=\"MainFrame\">新闻资讯管理</a></SPAN></TD></TR>\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/news/edit.jsp?method=ADDNEWS\" target=\"MainFrame\">发布新闻资讯</a></SPAN></TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("  <TD noWrap width=\"35%\">\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\"style=\"cursor:hand\" onclick=javascript:expand(4)>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=\"31\" background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\">&nbsp;</td>\r\n");
      out.write("    <TD background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\" >&nbsp;<IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/menu.gif\" align=absMiddle>注册会员管理</TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\" id=id_4 style=\"display:none\">\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/member/person.jsp\" target=\"MainFrame\">注册会员管理</a></SPAN></TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("  <TD noWrap width=\"35%\">\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\"style=\"cursor:hand\" onclick=javascript:expand(5)>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=\"31\" background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\">&nbsp;</td>\r\n");
      out.write("    <TD background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\" >&nbsp;<IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/menu.gif\" align=absMiddle>出租信息管理</TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\" id=id_5 style=\"display:none\">\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/out/index.jsp\" target=\"MainFrame\">出租信息管理</a></SPAN></TD></TR>\r\n");
      out.write(" <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/out/add.jsp?method=addOut\" target=\"MainFrame\">发布出租信息</a></SPAN></TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("  <TD noWrap width=\"35%\">\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\"style=\"cursor:hand\" onclick=javascript:expand(6)>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=\"31\" background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\">&nbsp;</td>\r\n");
      out.write("    <TD background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\" >&nbsp;<IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/menu.gif\" align=absMiddle>出售信息管理</TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\" id=id_6 style=\"display:none\">\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/sale/index.jsp\" target=\"MainFrame\">出售信息管理</a></SPAN></TD></TR>\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/sale/add.jsp?method=addSale\" target=\"MainFrame\">发布出售信息</a></SPAN></TD></TR>\r\n");
      out.write("  \r\n");
      out.write("   </TABLE>\r\n");
      out.write("  </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("  <TD noWrap width=\"35%\">\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\"style=\"cursor:hand\" onclick=javascript:expand(7)>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=\"31\" background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\">&nbsp;</td>\r\n");
      out.write("    <TD background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\" >&nbsp;<IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/menu.gif\" align=absMiddle>求租信息管理</TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\" id=id_7 style=\"display:none\">\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/in/index.jsp\" target=\"MainFrame\">求租信息管理</a></SPAN></TD></TR>\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/in/add.jsp?method=addIn\" target=\"MainFrame\">求租信息管理</a></SPAN></TD></TR>\r\n");
      out.write("  \r\n");
      out.write("   </TABLE>\r\n");
      out.write("  </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("  <TD noWrap width=\"35%\">\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\"style=\"cursor:hand\" onclick=javascript:expand(8)>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=\"31\" background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\">&nbsp;</td>\r\n");
      out.write("    <TD background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\" >&nbsp;<IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/menu.gif\" align=absMiddle>求购信息管理</TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\" id=id_8 style=\"display:none\">\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/buy/index.jsp\" target=\"MainFrame\">求购信息管理</a></SPAN></TD></TR>\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/buy/add.jsp?method=addBuy\" target=\"MainFrame\">求购信息管理</a></SPAN></TD></TR>\r\n");
      out.write("  \r\n");
      out.write("   </TABLE>\r\n");
      out.write("  </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  <TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("  <TD noWrap width=\"35%\">\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\"style=\"cursor:hand\" onclick=javascript:expand(9)>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=\"31\" background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\">&nbsp;</td>\r\n");
      out.write("    <TD background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\" >&nbsp;<IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/menu.gif\" align=absMiddle>交易信息管理</TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\" id=id_9 style=\"display:none\">\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/jy/yd.jsp\" target=\"MainFrame\">预定信息管理</a></SPAN></TD></TR>\r\n");
      out.write("  \r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/jy/dj.jsp\" target=\"MainFrame\">定金信息管理</a></SPAN></TD></TR>\r\n");
      out.write("  \r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/jy/ht.jsp\" target=\"MainFrame\">合同信息管理</a></SPAN></TD></TR>\r\n");
      out.write("  \r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/jy/sfk.jsp\" target=\"MainFrame\">收付款信息</a></SPAN></TD></TR>\r\n");
      out.write("   </TABLE>\r\n");
      out.write("  </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("   <TR ParentID=\"SystemLastArticle\" AllParentID=\"SystemLastArticle\">\r\n");
      out.write("  <TD noWrap width=\"35%\">\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\"style=\"cursor:hand\" onclick=javascript:expand(10)>\r\n");
      out.write("  <TR>\r\n");
      out.write("    <TD height=\"31\" background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\">&nbsp;</td>\r\n");
      out.write("    <TD background=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/linkbg1.gif\" >&nbsp;<IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/menu.gif\" align=absMiddle>统计报表管理</TD></TR>\r\n");
      out.write("  </TABLE>\r\n");
      out.write("  <TABLE width=\"100%\" border=\"0\" align=\"center\" id=id_10 style=\"display:none\">\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/tj/fw.jsp\" target=\"MainFrame\">房屋统计报表</a></SPAN></TD></TR>\r\n");
      out.write("  <TR ParentID=\"ConventionLastPic\" AllParentID=\"ConventionLastPic\">\r\n");
      out.write("    <TD noWrap width=\"35%\"><IMG src=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/images/bullet.gif\" \r\n");
      out.write("      align=absMiddle><SPAN style=\"CURSOR: default\"> <a href=\"");
      out.print(basePath );
      out.print(dir );
      out.write("/tj/xszj.jsp\" target=\"MainFrame\">销售租金报表</a></SPAN></TD></TR>\r\n");
      out.write("    </TABLE>\r\n");
      out.write("  </TD>\r\n");
      out.write("  </TR>\r\n");
      out.write("  </TBODY>\r\n");
      out.write("</TABLE>\r\n");
      out.write("</DIV>\r\n");
      out.write("    </TD>\r\n");
      out.write("    </TR>\r\n");
      out.write("    </TBODY>\r\n");
      out.write("    </TABLE>\r\n");
      out.write("    </TD></TR>\r\n");
      out.write("    </TBODY>\r\n");
      out.write("    </TABLE>\r\n");
      out.write("</BODY>\r\n");
} 
      out.write("\r\n");
      out.write("</HTML>\r\n");
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          out.clearBuffer();
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
